### ISSUE TITLE
 uninitialized constant ActiveMerchant::Billing::Integrations::Helper (NameError)

### ISSUE THREAD

**Issue by ZhangHanDong** [activemerchant/active_merchant#1357]
gem 'activemerchant', "~> 1.44.0", :require => 'active_merchant'

No such problem when i  use version 1.43.3

**Comment by jengweneg** [comment]
Hello,
I am running into a similar type of issue.
After successfully instaling catarse_paypa_express gem, i can"t start the server because of the following error.
I have installed the most recent version of activemerchant (1.76.0)
Please help

bin/rails server -d -p3005
/usr/src/fiatope/config/application.rb:10: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:85:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'catarse_paypal_express'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveMerchant::Billing::Integrations
Backtrace for gem load error is:
/usr/local/rvm/gems/ruby-2.1.3/gems/catarse_paypal_express-3.0.2/lib/catarse_paypal_express/gateway.rb:3:in `<class:Gateway>'
/usr/local/rvm/gems/ruby-2.1.3/gems/catarse_paypal_express-3.0.2/lib/catarse_paypal_express/gateway.rb:2:in `<module:CatarsePaypalExpress>'
/usr/local/rvm/gems/ruby-2.1.3/gems/catarse_paypal_express-3.0.2/lib/catarse_paypal_express/gateway.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/catarse_paypal_express-3.0.2/lib/catarse_paypal_express.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:82:in `block (2 levels) in require'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `each'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:77:in `block in require'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `each'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler/runtime.rb:66:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/bundler-1.15.0/lib/bundler.rb:108:in `require'
/usr/src/fiatope/config/application.rb:12:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:79:in `require'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:79:in `block in server'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `tap'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:76:in `server'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.1.5/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
/usr/local/rvm/gems/ruby-2.1.3/gems/railties-4.1.5/lib/rails/commands.rb:17:in `<top (required)>'
/usr/src/fiatope/bin/rails:8:in `require'
/usr/src/fiatope/bin/rails:8:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.3/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
/usr/local/rvm/gems/ruby-2.1.3/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
/usr/local/rvm/gems/ruby-2.1.3/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
/usr/local/rvm/gems/ruby-2.1.3/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.3/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
