### ISSUE TITLE
Methods to receive card tokens

### ISSUE THREAD

**Issue by vhailor303** [activemerchant/active_merchant#1763]
I've been toying around with `active_merchant` and recurring payments lately. I noticed, that in some cases (if not all - I've tried Worldpay Online and Stripe) there is no public method to get the card token and to call the gateway to charge a payment using that token. Most of related methods are private.
Is there any good reason behind it? I'm pretty tired of hacking this around and eager to change it.

**Comment by ntalbott** [comment]
@vhailor303 the typical combo in ActiveMerchant for this is `store` (to create a token, returned in `Response#authorization`), and `purchase` (which simply takes the token `String` in place of a credit card). Stripe is weird in that it has a somewhat half-baked `StripePaymentToken` model instead of a `String`. Worldpay Online simply hasn't had the necessary functionality implemented, but a good example of it is the functionality just added to the ActiveMerchant adapter.

**Comment by vhailor303** [comment]
@ntalbott what if I want to store a credit card number without performing a `purchase` action? From the code for this exact gateway (Worldpay Online Payments Gateway) I see it is possible, as this is the action performed first ([here](https://github.com/activemerchant/active_merchant/blob/dcc2f49d60486d9a08fcac20059c537ab1772931/lib/active_merchant/billing/gateways/worldpay_online_payments.rb#L77) - if I understand what it does correctly). There is also a possibility to pay using only this token - I managed to do it using those private methods, though doing some ugly hacks by the way.

But from what I can see, Stripe will be easier to cooperate with than I thought at first. Anyway, thanks for a quick response.

**Comment by ntalbott** [comment]
@vhailor303 storing without doing a `purchase` is the use case for the `store` API method. It just hasn't been implemented in the Worldpay Online adapter.
