### ISSUE TITLE
"undefined method `+' for nil:NilClass" when trying to validate a credit card

### ISSUE THREAD

**Issue by damiangalindo** [activemerchant/active_merchant#1889]
I'm getting this error ```undefined method `+' for nil:NilClass``` when executing the method valid? in credit card, I've traced the error to this line ```errors = validate_essential_attributes + validate_verification_value``` inside the activemerchant gem in the file credit_card.rb, thanks in advance for any help

**Comment by sdball** [comment]
That would mean that the `validate_essential_attributes` variable is nil. Which would be strange since that method declares, modifies, and returns an empty array variable.

Can you share steps to reproduce?

And just to get the full story, what version of active_merchant are you using? Are you including The Rails-specific methods with `require "active_merchant/billing/rails"`?

Can you share the results of running this code?

```
credit_card = CreditCard.new
credit_card.valid?
```

**Comment by damiangalindo** [comment]
Hello @sdball, I'm sorry i hadn't closed this before, we solved the issue, the method was overwritted in our end, thanks anyway.

**Comment by sdball** [comment]
No problem! I'm glad you got it worked out.
