### ISSUE TITLE
Stripe: Store method does not cleanly accept string inputs interpreted as tokens

### ISSUE THREAD

**Issue by bizla** [activemerchant/active_merchant#2130]
Currently the Stripe gateway integration doesn't have a tested code path for accepting [Stripe card tokens](https://stripe.com/docs/stripe.js?#collecting-card-details).
Specifically, an explicit call to `card_brand` throws an exception because of a conditional check that assumes that the input is a credit-card-like object, whereas for other methods like `purchase`, a string input is handled correctly; it's interpreted as a Stripe token string. 

See the discussion in https://github.com/activemerchant/active_merchant/pull/2098 for an example of an affected consumer.

**Comment by jordan-brough** [comment]
Can we move `StripePaymentToken` out of the `private` area ([here](https://github.com/activemerchant/active_merchant/blob/4881e20572604eec6cf787d38e82708e58bd71c5/lib/active_merchant/billing/gateways/stripe.rb#L269-L275)) so that it's a bit more prominent?  Or else move it to its own file?  Also can we add a bit of documentation to it?  I'm happy to submit a PR for any of that if you'd like.

I ask because `StripePaymentToken` is now something that can be used across the board in `StripeGateway` and we have public methods that expect to receive it (e.g. `StripeGateway#store`).
