### ISSUE TITLE
Does active_merchant supports integeration with Payfort and BEE

### ISSUE THREAD

**Issue by helsayed** [activemerchant/active_merchant#2294]

**Comment by pablofullana** [comment]
Hey, are there any updates on this? I'm especially interested in the Payfort integration

**Comment by davidsantoso** [comment]
@helsayed we looked into adding Payfort however their API doesn't accept PAN data directly. The API assumes tokenization via their JS library and passing that token through to run a transaction. At this point, gateway adapters in Active Merchant are scoped to not being dependent on external libraries to run a transaction.

I'm not sure about BEE, you're welcome to explore adding it. See our [contribution wiki page](https://github.com/activemerchant/active_merchant/wiki/Contributing) for more details.

**Comment by ahtesham78** [comment]
Any plan for adding Payfort Payment Gateway, as I see open pull request to merge.
https://github.com/activemerchant/active_merchant/pull/2984

**Comment by obahareth** [comment]
@davidsantoso That's not the case with Payfort anymore (and at least since late 2018), what they call [Merchant Page 2.0](https://docs.payfort.com/docs/api/build/index.html#features40) accepts PAN data directly, you can call their API to tokenize a card and you pass the PAN data to that API. The JavaScript library or any other external dependency are not required anymore.
