### ISSUE TITLE
Tokenizing credit card

### ISSUE THREAD

**Issue by bcackerman** [activemerchant/active_merchant#2612]
How can we tokenize the credit card client-side before sending it to our server to process? It seems less secure to send the cc information to the server for processing.

**Comment by EssenKh** [comment]
@bcackerman  interesting i just get an issue there. did you get any solution ?

**Comment by bdewater** [comment]
Tokenization is usually done by the payment gateway (e.g. Stripe or Braintree tokens, specific to the gateway) or the network (Visa, MasterCard, etc. used for example by Apple Pay, tokens look like normal credit card numbers for backwards compatibility). If you don't have the security expertise and/or don't want to handle the PCI DSS compliance you're better off not processing raw credit card data, absolutely.

I'm closing this issue since building your own tokenization solution (not something I would recommend) or support for integrating tokenization solutions on your website is not the scope of the ActiveMerchant project.
