### ISSUE TITLE
ActiveMerchant with Stripe, Tokenizing credit card

### ISSUE THREAD

**Issue by EssenKh** [activemerchant/active_merchant#2620]
I am using Stripe Gateway and i got this error: 
```
--- !ruby/object:ActiveMerchant::Billing::Response
params:
  error:
    type: invalid_request_error
    message: Sending credit card numbers directly to the Stripe API is generally unsafe.
      We suggest you use test tokens that map to the test card you are using, see
      https://stripe.com/docs/testing.
```

How can we use tokens in that side ?

**Comment by Ligator** [comment]
+1

**Comment by jasonwebster** [comment]
Simply use the card token as the second argument to `#purchase` or `#authorize` instead of a card number.

**Comment by nfriend21** [comment]
Just "passing the card token" is not really clear enough.  I expected that to be the token object.  It is actually the token ID that you need to pass, otherwise you will get the error:

{"error"=>{"type"=>"invalid_request_error", "message"=>"Must provide source or customer."}}

I think the docs should be more explicit there.
