### ISSUE TITLE
Unexpected error from Stripe about regarding unsafety of sending card numbers directly to Stripe API

### ISSUE THREAD

**Issue by Azdaroth** [activemerchant/active_merchant#2679]
We've been using activemerchant and Stripe integration for a long time without any problems and recently started to experience some issues.  Stripe API has started to respond with the following error message: "Sending credit card numbers directly to the Stripe API is generally unsafe. To continue processing use Stripe.js, the Stripe mobile bindings, or Stripe elements." but nothing has changed as far as the code goes.  We are currently at 1.60.0 version.

Are you aware of any issues with Stripe, like a possible breaking change in their API, which is not handled?

**Comment by Azdaroth** [comment]
Any update here? Has anyone experienced that?

**Comment by guaguasi** [comment]
This isn't an activemerchant issue, it's a configuration issue on the Stripe side. I haven't done it myself, but there's an option somewhere in the Stripe dashboard, behind a couple of scary prompts, that needs to be enabled. Something about allowing unsafe transactions.

**Comment by Azdaroth** [comment]
Thanks @guaguasi for the response. 

If it's a matter of configuration, does it mean that, in general, using Stripe via activemerchant (or just any other way which accesses their API) is considered unsafe by Stripe?

**Comment by guaguasi** [comment]
In their eyes, it does appear that way. I think there might be an increase in transaction fees, too, though I'm not certain. I have yet to fiddle with the Stripe JS library, opting for the "unsafe" route, but below is how Square works and I believe they are similar.

Square has their own activemerchant extension that handles things "properly" in conjunction with their JS library and iframes. The JS library rerenders the CC fields of the form as iframes so the information is submitted to them directly. The library then returns a nonce to us as a reference to the CC information stored on their system. Their activemerchant extension uses the nonce instead of a CC number to submit the purchase information using the same syntax as any other gateway. It's not necessary but it does help keep things somewhat standard.

I'm not entirely sure what the difference is, but I assume that it's because they trust their own server's security over a random other server.

**Comment by Azdaroth** [comment]
Thanks @guaguasi for the info, we might get in touch with someone from Stripe soon, so it should be clearer why it is the case and if there is any possible workaround that doesn't look like doing something insecure.

**Comment by padi** [comment]
@Azdaroth any update on this? I think it might related to https://github.com/activemerchant/active_merchant/issues/2620

I'm also encountering the same exact error.

**Comment by Azdaroth** [comment]
@padi Apparently,  to use activemerchant with new Stripe accounts, the setting for processing "unsafe" transactions must be enabled.

**Comment by padi** [comment]
@Azdaroth Thanks!

For everyone else who might stumble upon this warning and want to perhaps temporarily get past it,
this can be found under `Business settings > Integration` in your Stripe Dashboard (https://dashboard.stripe.com/account/integration/settings).

**Comment by jasonwebster** [comment]
For anyone who's curious as to _why_:

Submitting plain PANs to Stripe (or any gateway, for that matter) _requires_ that your system is 100% PCI compliant. This is essentially a toggle for "ok I know what I'm doing." The fact that Stripe is doing this by default is a good thing.

**Comment by padi** [comment]
@jasonwebster Thanks for pointing that out.

I've investigated further and you don't want to get through PCI compliance, the only secure option you have is to pass those credit card information directly from the front-end form fields to stripe using Stripe.js' `createToken` and use that token in the backend instead.

Reference: https://stripe.com/docs/stripe-js/reference#stripe-create-token

**Comment by bpollack** [comment]
Since this doesn't appear to be an actual bug, I'm closing the issue. We can always find somewhere to mark in the docs if we really need to.
