### ISSUE TITLE
Redsys REST API

### ISSUE THREAD

**Issue by varyonic** [activemerchant/active_merchant#3548]
I've been told the XML endpoint at sis/operaciones has been deprecated in favor of sis/rest and will be retired soon. Can anyone confirm this? @britth

**Comment by varyonic** [comment]
@esmitperez @curiousepic @britth Any plans to work on this?

**Comment by curiousepic** [comment]
@varyonic Thanks for the heads up, we will look into it.

**Comment by curiousepic** [comment]
@varyonic FYI, after confirming with Banco Sabadell/Redsys, Spreedly will not be implementing the REST API in ActiveMerchant by June 1, but we will be adding the capability to request SCA exemptions so that they are properly routed to the WebService V2 endpoint for PSD2 compliance, in the same manner that transactions with `execute_threed` enabled. That endpoint and the Operaciones endpoint will both remain functional past June 1.

We will be looking into adding the full REST API endpoint as a new gateway as time permits.

**Comment by varyonic** [comment]
See https://github.com/varyonic/activemerchant-redsys_rest

**Comment by curiousepic** [comment]
@varyonic Nice! If you're willing, we would be happy to bring it into AM proper, when we're able too review.

**Comment by curiousepic** [comment]
@varyonic Would you be willing to open a generalized PR against the main branch?

**Comment by curiousepic** [comment]
Thanks @varyonic, we will likely be updating and merging this in the near-middle future. Closing this issue.
